name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*
permissions:
  contents: write
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*