name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*
permissions:
  contents: write
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun ./scripts/fix.bun.ts
      - run: bun run build:bin
      # - name: Upload
      #   if: github.ref != 'refs/tags/v*.*.*'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: |
      #       build/*
      - name: Release
        # if: github.ref == 'refs/tags/v*.*.*'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*
          body: |
            > [!IMPORTANT]
            > If you are using macos, you will need to run following commands to be able to run these binaries:
            > ```shellscript
            > chmod +x ./experiment-*
            > xattr -d com.apple.quarantine ./experiment-*
            > ```