name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*
permissions:
  contents: write
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build:bin
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*
          body: |
            > [!IMPORTANT]
            > If you are using macOS or Linux, you need to give the downloaded file permission to execute:
            > ```shellscript
            > chmod +x ./experiment-*
            > ```
            > For macOS users specifically, removing quarantine is also necessary:
            > ```shellscript
            > xattr -d com.apple.quarantine ./experiment-*
            > ```